language: c++
sudo: required

before_install:
  - echo "yes" | sudo apt-add-repository ppa:avsm/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y ocaml ocaml-native-compilers camlp4-extra opam \
    libgtk2.0-dev

script: bash -ex .travis-ci.sh

env:
  - OCAML_VERSION=4.04.0 OPAM_VERSION=1.2.2

dist: xenial
